#!/usr/bin/env bash
colors.sh #Set up colors
echo "${GREEN}setup::main"

read -p "What is your Git Name?" name
git config user.name "$name"
GIT_AUTHOR_NAME=$name
GIT_COMMIT_NAME=$name

read -p "What is your Git Email?" email
git config user.email $email
GIT_AUTHOR_EMAIL=$email
GIT_COMMIT_EMAIL=$email

cd C:

echo "Installing Notepad++..."
cd "Program Files (x86)/"
mkdir -p "Notepad++"
wget http://notepad-plus-plus.org/repository/6.x/6.7.7/npp.6.7.7.bin.zip
unzip npp.6.7.7.bin.zip -d Notepad++
rm npp.6.7.7.bin.zip

echo "Installing Python..."
wget http://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz
tar -xzf Python-2.7.9.tgz
cd Python-2.7.9
./configure
make
sudo make install
export PATH=$PATH:C:\Python-2.7.9\
cd C:
