#!/usr/bin/env bash
colors.sh #Set up colors
echo "${GREEN}setup::main"

read -p "What is your Git Name?" name
git config --global user.name "$name"
GIT_AUTHOR_NAME=$name
GIT_COMMIT_NAME=$name

read -p "What is your Git Email?" email
git config --global user.email $email
GIT_AUTHOR_EMAIL=$email
GIT_COMMIT_EMAIL=$email

cd C:

echo "Installing Notepad++..."
cd "Program Files (x86)/"
mkdir -p Notepad++
cd Notepad++
wget http://notepad-plus-plus.org/repository/6.x/6.7.7/npp.6.7.7.bin.zip
unzip npp.6.7.7.bin.zip -d Notepad++
rm npp.6.7.7.bin.zip
export PATH="$PATH;C:\Program Files (x86)\Notepad++"
cd C:

echo "Installing Python..."
wget http://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz
tar -xzf Python-2.7.9.tgz
cd Python-2.7.9
./configure
make
sudo make install
export PATH=$PATH;C:\Python-2.7.9\

echo "Installing pip..."
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py

echo "Installing pip packages..."
pip isntall thefuck
alias fuck='eval $(thefuck $(fc -ln -1)); history -r'
cd C:

echo "Installing node.js..."
git clone git://github.com/ry/node.git
cd node
./configure
make
sudo make install

echo "Installing Strawberry Perl..."
mkdir -p Perl
cd Perl
wget http://strawberryperl.com/download/5.20.2.1/strawberry-perl-5.20.2.1-64bit-portable.zip
upzip strawberry-perl-5.20.2.1-64bit-portable.zip
rm strawberry-perl-5.20.2.1-64bit-portable.zip
export PATH=$PATH;C:\Perl\
cd C:

echo "Installing Java..."
mkdir -p Java && cd Java
# wget http://download.oracle.com/otn-pub/java/jdk/8u45-b15/jdk-8u45-windows-i586.exe
# ./jdk-8u45-windows-i586.exe
# read -p "Hit [Enter] once you've gone through the Java installation."
wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u40-b26/jdk-8u40-linux-x64.tar.gz -O -
tar -zxvf -
cd C:
