#!/usr/bin/env bash
echo "setup::main"

read -p "What is your Git Name?" name
git config user.name "$name"
GIT_AUTHOR_NAME=$name
GIT_COMMIT_NAME=$name

read -p "What is your Git Email?" email
git config user.email $email
GIT_AUTHOR_EMAIL=$email
GIT_COMMIT_EMAIL=$email
